version: '3.8'

services:
  app:
    build: .
    container_name: contract-generator
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - templates:/app/templates
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ROOT_EMAIL=${ROOT_EMAIL}
      - ROOT_PASSWORD_HASH=${ROOT_PASSWORD_HASH}

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  templates: