spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mvc:
    locale: uk
  messages:
    basename: i18n/messages
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: none

app:
  root-email: ${ROOT_EMAIL}
  root-password-hash: ${ROOT_PASSWORD_HASH}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.maksym.odnokozov: TRACE